### PR TITLE
Bringing ethberlin contracts into main repo

### PR DESCRIPTION
**Pull request by nickreynolds**
- bringing in contracts, migrations, helper scripts, and tests from ethberlin repo. 
- fixing tests.

### CODE REVIEW

**Comment by tarrencev** [comment]
Hey @nickreynolds, I think we should pull these in over multiple PR's, so we can better review them implementations. I wrote these hastily and I'm sure there are issues/security considerations we should discuss before merging 😅

**Comment by nickreynolds** [comment]
what do you think would be the best way to bring them over? start by bringing the tokens over 1 by 1?

**Comment by tarrencev** [comment]
Yeah I think that makes sense. We could also use https://github.com/tarrencev/curve-bonded-tokens so it's not necessary to pull in all the bonding curve stuff

**Comment by nickreynolds** [comment]
alright, closing this PR and going to do it more piecemeal

**Pull request closed without merging**
